/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    IconFontIcon: typeof import('./src/components/Icon/IconFontIcon.vue')['default']
    Iconify: typeof import('./src/components/Icon/Iconify.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconNetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
    IconReloadPrompt: typeof import('./src/components/Icon/ReloadPrompt.vue')['default']
    IconSvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    NetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
    Notice: typeof import('./src/components/Notice/Notice.vue')['default']
    NoticeMessage: typeof import('./src/components/notice/notice-message.vue')['default']
    NoticeMessageList: typeof import('./src/components/Notice/NoticeMessageList.vue')['default']
    Notification: typeof import('./src/components/Notice/Notification.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/Menu/SubMenu.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
  }
}
